apiVersion: apps/v1
kind: Deployment
metadata:
  name: pal-tracker
spec:
  template:
    spec:
      containers:
        - name: pal-tracker-container
          image: raymondfanglimin/pal-tracker:build-github.run_number
          env:
          - name: SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE
            value: "1"
